name: weekly pre-commit autoupdate

on:
  workflow_dispatch:
  schedule:
    - cron: "0 16 * * 0"

jobs:
  auto-update-pre-commit:
    uses: devmarkusb/gh-workflows/.github/workflows/update-pre-commit.yml@main
    secrets:
      APP_ID: ${{ secrets.AUTO_PR_BOT_APP_ID }}
      PRIVATE_KEY: ${{ secrets.AUTO_PR_BOT_PRIVATE_KEY }}
